#ifndef INTEGRAL_IMAGE_PARALLEL_DEFINE_H
#define INTEGRAL_IMAGE_PARALLEL_DEFINE_H

#define INPUT_SIZE 4

#define BLOCK_SIZE_T 2
#define TILE_SIZE_T 2

#define BLOCK_SIZE_S 2

#endif //INTEGRAL_IMAGE_PARALLEL_DEFINE_H
