#ifndef INTEGRAL_IMAGE_PARALLEL_DEFINE_H
#define INTEGRAL_IMAGE_PARALLEL_DEFINE_H

#define INPUT_SIZE 1024*8

#define BLOCK_SIZE_T 8
#define TILE_SIZE_T 32

#define BLOCK_SIZE_S 128

#endif //INTEGRAL_IMAGE_PARALLEL_DEFINE_H
